/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nutritionalprogram.View;

import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JScrollPane;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import javax.swing.SpinnerNumberModel;
import nutritionalprogram.Controller.CreateMenuController;

/**
 *
 * @author Luana Franciele
 */
public class CreateMenuPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateMenuPanel1
     */
    private JScrollPane scrollPanel;
    private CreateMenuController controller;
    private String patientName;
    private PatientPanel patientPanel;
    
    public CreateMenuPanel(JScrollPane scrollPanel, String patientName, PatientPanel patientPanel) {  
        initComponents();
        this.patientPanel = patientPanel;
        this.patientName = patientName;
        this.scrollPanel = scrollPanel;
        this.controller = new CreateMenuController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        patientBaseInfos = new javax.swing.JPanel();
        jLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        lblMeal = new javax.swing.JLabel();
        cbMeal = new javax.swing.JComboBox<>();
        lblFoodGroup = new javax.swing.JLabel();
        cbFoodGroup = new javax.swing.JComboBox<>();
        lblFoodName = new javax.swing.JLabel();
        cbFoodName = new javax.swing.JComboBox<>();
        lblPortion = new javax.swing.JLabel();
        spinPortion = new javax.swing.JSpinner();
        checkSubstitutions = new javax.swing.JCheckBox();
        lblShowMenu = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listShowMenu = new javax.swing.JList<>();
        btnDeleteAll = new javax.swing.JButton();
        addMenuBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();

        setOpaque(false);

        patientBaseInfos.setBackground(new java.awt.Color(41, 182, 246));
        patientBaseInfos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel.setText("Nome:");

        nameLabel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        nameLabel.setText("Nome");

        javax.swing.GroupLayout patientBaseInfosLayout = new javax.swing.GroupLayout(patientBaseInfos);
        patientBaseInfos.setLayout(patientBaseInfosLayout);
        patientBaseInfosLayout.setHorizontalGroup(
            patientBaseInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patientBaseInfosLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        patientBaseInfosLayout.setVerticalGroup(
            patientBaseInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patientBaseInfosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(patientBaseInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nameLabel)
                    .addComponent(jLabel, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(115, 232, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblName.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblName.setText("Nome do cardápio:");

        tfName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNameActionPerformed(evt);
            }
        });

        lblMeal.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblMeal.setText("Refeição:");

        cbMeal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "café da manhã", "lanche", "almoço", "lanche da tarde", "jantar", "ceia" }));
        cbMeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMealActionPerformed(evt);
            }
        });

        lblFoodGroup.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblFoodGroup.setText("Grupo:");

        cbFoodGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFoodGroupActionPerformed(evt);
            }
        });

        lblFoodName.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblFoodName.setText("Alimento:");

        cbFoodName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFoodNameActionPerformed(evt);
            }
        });

        lblPortion.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblPortion.setText("Porção:");

        double current = 0.0;
        double min = -100.0;
        double max = 100.0;
        double step = 0.01;
        spinPortion.setModel(new SpinnerNumberModel(current, min, max, step));

        checkSubstitutions.setBackground(new java.awt.Color(115, 232, 255));
        checkSubstitutions.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        checkSubstitutions.setSelected(true);
        checkSubstitutions.setText("Substituições");

        lblShowMenu.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblShowMenu.setText("Café da manhã:");

        jScrollPane1.setViewportView(listShowMenu);

        btnDeleteAll.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnDeleteAll.setText("Limpar");
        btnDeleteAll.setBorder(null);
        btnDeleteAll.setBorderPainted(false);
        btnDeleteAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteAllActionPerformed(evt);
            }
        });

        addMenuBtn.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        addMenuBtn.setText("Adicionar");

        saveBtn.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        saveBtn.setText("Salvar");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        cancelBtn.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cancelBtn.setText("Cancelar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblFoodGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFoodName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPortion, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMeal, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkSubstitutions, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbMeal, 0, 203, Short.MAX_VALUE)
                    .addComponent(cbFoodGroup, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbFoodName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(spinPortion)
                    .addComponent(tfName)
                    .addComponent(lblName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblShowMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(btnDeleteAll, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(addMenuBtn)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblShowMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDeleteAll, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addMenuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(lblMeal, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbMeal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblFoodGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbFoodGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblFoodName, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbFoodName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblPortion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spinPortion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(checkSubstitutions)))
                .addGap(18, 18, 18)
                .addComponent(cancelBtn)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(patientBaseInfos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(patientBaseInfos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public JList<String> getListShowMenu() {
        return listShowMenu;
    }
    
    
    private void tfNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNameActionPerformed

    private void cbMealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMealActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMealActionPerformed

    private void cbFoodGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFoodGroupActionPerformed
        
    }//GEN-LAST:event_cbFoodGroupActionPerformed

    private void btnDeleteAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteAllActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteAllActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveBtnActionPerformed

    private void cbFoodNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFoodNameActionPerformed
        
    }//GEN-LAST:event_cbFoodNameActionPerformed

    public JScrollPane getScrollPanel() {
        return scrollPanel;
    }

    public String getPatientName() {
        return patientName;
    }

    public PatientPanel getPatientPanel() {
        return patientPanel;
    }
    
    public JButton getAddMenuBtn() {
        return addMenuBtn;
    }

    public JButton getBtnDeleteAll() {
        return btnDeleteAll;
    }

    public JButton getCancelBtn() {
        return cancelBtn;
    }

    public JComboBox<String> getCbFoodGroup() {
        return cbFoodGroup;
    }

    public JComboBox<String> getCbFoodName() {
        return cbFoodName;
    }

    public JComboBox<String> getCbMeal() {
        return cbMeal;
    }

    public JCheckBox getCheckSubstitutions() {
        return checkSubstitutions;
    }

    public JLabel getLblMeal() {
        return lblMeal;
    }

    public JLabel getNameLabel() {
        return nameLabel;
    }

    public JButton getSaveBtn() {
        return saveBtn;
    }

    public JSpinner getSpinPortion() {
        return spinPortion;
    }

    public JTextField getTfName() {
        return tfName;
    }

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addMenuBtn;
    private javax.swing.JButton btnDeleteAll;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JComboBox<String> cbFoodGroup;
    private javax.swing.JComboBox<String> cbFoodName;
    private javax.swing.JComboBox<String> cbMeal;
    private javax.swing.JCheckBox checkSubstitutions;
    private javax.swing.JLabel jLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFoodGroup;
    private javax.swing.JLabel lblFoodName;
    private javax.swing.JLabel lblMeal;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPortion;
    private javax.swing.JLabel lblShowMenu;
    private javax.swing.JList<String> listShowMenu;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JPanel patientBaseInfos;
    private javax.swing.JButton saveBtn;
    private javax.swing.JSpinner spinPortion;
    private javax.swing.JTextField tfName;
    // End of variables declaration//GEN-END:variables
}
