/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nutritionalprogram.View;

import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author Luana Franciele
 */
public class PatientPanel extends javax.swing.JPanel {

    /**
     * Creates new form PatientPanel
     */
    
    public PatientPanel() {
        initComponents();
        
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        patientBaseInfos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        ageLabel = new javax.swing.JLabel();
        sexLabel = new javax.swing.JLabel();
        hightLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        backDateBtn = new javax.swing.JButton();
        dateLabel = new javax.swing.JLabel();
        nextDateBtn = new javax.swing.JButton();
        patientWeightInfos = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        currentWeightLabel = new javax.swing.JLabel();
        goalWeightLabel = new javax.swing.JLabel();
        bodyfatLabel = new javax.swing.JLabel();
        imcLabel = new javax.swing.JLabel();
        differenceWeightLabel = new javax.swing.JLabel();
        patientMeasuresInfos = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        shouldersLabel = new javax.swing.JLabel();
        chestLabel = new javax.swing.JLabel();
        leftArmLabel = new javax.swing.JLabel();
        rightArmLabel = new javax.swing.JLabel();
        waistLabel = new javax.swing.JLabel();
        hipLabel = new javax.swing.JLabel();
        rightLegLabel = new javax.swing.JLabel();
        leftLegLabel = new javax.swing.JLabel();
        rightCalfLabel = new javax.swing.JLabel();
        leftCalfLabel = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        deleteInfoBtn = new javax.swing.JButton();
        addInfoBtn = new javax.swing.JButton();

        patientBaseInfos.setBackground(new java.awt.Color(102, 255, 102));
        patientBaseInfos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setText("Perfil do paciente");

        nameLabel.setText("Nome:");

        ageLabel.setText("Idade:");

        sexLabel.setText("Sexo:");

        hightLabel.setText("Altura:");

        jLabel2.setText("Nome:");

        javax.swing.GroupLayout patientBaseInfosLayout = new javax.swing.GroupLayout(patientBaseInfos);
        patientBaseInfos.setLayout(patientBaseInfosLayout);
        patientBaseInfosLayout.setHorizontalGroup(
            patientBaseInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patientBaseInfosLayout.createSequentialGroup()
                .addGroup(patientBaseInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(patientBaseInfosLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(patientBaseInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ageLabel)
                            .addComponent(jLabel1)))
                    .addGroup(patientBaseInfosLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 211, Short.MAX_VALUE)
                .addGroup(patientBaseInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sexLabel)
                    .addComponent(hightLabel))
                .addGap(227, 227, 227))
        );
        patientBaseInfosLayout.setVerticalGroup(
            patientBaseInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patientBaseInfosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(patientBaseInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(sexLabel)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(patientBaseInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageLabel)
                    .addComponent(hightLabel))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        backDateBtn.setText("<-");

        dateLabel.setText("20/04/200");

        nextDateBtn.setText("->");

        patientWeightInfos.setBackground(new java.awt.Color(102, 255, 102));

        jLabel6.setText("Peso do paciente");

        currentWeightLabel.setText("Atual:");

        goalWeightLabel.setText("Meta:");

        bodyfatLabel.setText("Gordura corporal:");

        imcLabel.setText("IMC:");

        differenceWeightLabel.setText("Diferença:");

        javax.swing.GroupLayout patientWeightInfosLayout = new javax.swing.GroupLayout(patientWeightInfos);
        patientWeightInfos.setLayout(patientWeightInfosLayout);
        patientWeightInfosLayout.setHorizontalGroup(
            patientWeightInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patientWeightInfosLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(patientWeightInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(patientWeightInfosLayout.createSequentialGroup()
                        .addGroup(patientWeightInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(currentWeightLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bodyfatLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(63, 63, 63)
                        .addGroup(patientWeightInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(goalWeightLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                            .addComponent(imcLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(differenceWeightLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(77, 77, 77))
        );
        patientWeightInfosLayout.setVerticalGroup(
            patientWeightInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patientWeightInfosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(29, 29, 29)
                .addGroup(patientWeightInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(currentWeightLabel)
                    .addComponent(goalWeightLabel)
                    .addComponent(differenceWeightLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(patientWeightInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bodyfatLabel)
                    .addComponent(imcLabel))
                .addGap(30, 30, 30))
        );

        patientMeasuresInfos.setBackground(new java.awt.Color(102, 255, 102));
        patientMeasuresInfos.setPreferredSize(new java.awt.Dimension(0, 143));

        jLabel9.setText("Medidas");

        shouldersLabel.setText("Ombros:");

        chestLabel.setText("Peitoral:");

        leftArmLabel.setText("Braço e.:");

        rightArmLabel.setText("Braço d.:");

        waistLabel.setText("Cintura:");

        hipLabel.setText("Quadril:");

        rightLegLabel.setText("Perna d.:");

        leftLegLabel.setText("Perna e.:");

        rightCalfLabel.setText("Panturrilha d.:");

        leftCalfLabel.setText("Panturrilha e.:");

        javax.swing.GroupLayout patientMeasuresInfosLayout = new javax.swing.GroupLayout(patientMeasuresInfos);
        patientMeasuresInfos.setLayout(patientMeasuresInfosLayout);
        patientMeasuresInfosLayout.setHorizontalGroup(
            patientMeasuresInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, patientMeasuresInfosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(patientMeasuresInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(patientMeasuresInfosLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel9))
                    .addComponent(shouldersLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chestLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(leftArmLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(rightArmLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(waistLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 217, Short.MAX_VALUE)
                .addGroup(patientMeasuresInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(hipLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rightLegLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(leftLegLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rightCalfLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                    .addComponent(leftCalfLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(140, 140, 140))
        );
        patientMeasuresInfosLayout.setVerticalGroup(
            patientMeasuresInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patientMeasuresInfosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(patientMeasuresInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shouldersLabel)
                    .addComponent(hipLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(patientMeasuresInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chestLabel)
                    .addComponent(rightLegLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(patientMeasuresInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(leftArmLabel)
                    .addComponent(leftLegLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(patientMeasuresInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rightArmLabel)
                    .addComponent(rightCalfLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(patientMeasuresInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(leftCalfLabel)
                    .addComponent(waistLabel))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jButton3.setText("Criar novo cardápio");

        jButton4.setText("Ver cardápios");

        deleteInfoBtn.setText("Deletar");

        addInfoBtn.setText("Adicionar informações");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backDateBtn)
                        .addGap(18, 18, 18)
                        .addComponent(dateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nextDateBtn)
                        .addGap(18, 18, 18)
                        .addComponent(deleteInfoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(addInfoBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(patientBaseInfos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(patientWeightInfos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(patientMeasuresInfos, javax.swing.GroupLayout.DEFAULT_SIZE, 669, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(patientBaseInfos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nextDateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(backDateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(deleteInfoBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addInfoBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(patientWeightInfos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(patientMeasuresInfos, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    public JButton getAddInfoBtn() {
        return addInfoBtn;
    }

    public JButton getDeleteInfoBtn() {
        return deleteInfoBtn;
    }
    
    public JButton getBackDateBtn() {
        return backDateBtn;
    }

    public JButton getNextDateBtn() {
        return nextDateBtn;
    }

    
    
    public JLabel getAgeLabel() {
        return ageLabel;
    }

    public JLabel getHightLabel() {
        return hightLabel;
    }

    public JLabel getNameLabel() {
        return nameLabel;
    }

    public JLabel getSexLabel() {
        return sexLabel;
    }

    public JLabel getBodyfatLabel() {
        return bodyfatLabel;
    }

    public JLabel getChestLabel() {
        return chestLabel;
    }

    public JLabel getCurrentWeightLabel() {
        return currentWeightLabel;
    }

    public JLabel getDateLabel() {
        return dateLabel;
    }

    public JLabel getDifferenceWeightLabel() {
        return differenceWeightLabel;
    }

    public JLabel getGoalWeightLabel() {
        return goalWeightLabel;
    }

    public JLabel getHipLabel() {
        return hipLabel;
    }

    public JLabel getImcLabel() {
        return imcLabel;
    }

    public JLabel getLeftArmLabel() {
        return leftArmLabel;
    }

    public JLabel getLeftCalfLabel() {
        return leftCalfLabel;
    }

    public JLabel getLeftLegLabel() {
        return leftLegLabel;
    }

    public JLabel getRightArmLabel() {
        return rightArmLabel;
    }

    public JLabel getRightCalfLabel() {
        return rightCalfLabel;
    }

    public JLabel getRightLegLabel() {
        return rightLegLabel;
    }

    public JLabel getShouldersLabel() {
        return shouldersLabel;
    }

    public JLabel getWaistLabel() {
        return waistLabel;
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addInfoBtn;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JButton backDateBtn;
    private javax.swing.JLabel bodyfatLabel;
    private javax.swing.JLabel chestLabel;
    private javax.swing.JLabel currentWeightLabel;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JButton deleteInfoBtn;
    private javax.swing.JLabel differenceWeightLabel;
    private javax.swing.JLabel goalWeightLabel;
    private javax.swing.JLabel hightLabel;
    private javax.swing.JLabel hipLabel;
    private javax.swing.JLabel imcLabel;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel leftArmLabel;
    private javax.swing.JLabel leftCalfLabel;
    private javax.swing.JLabel leftLegLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JButton nextDateBtn;
    private javax.swing.JPanel patientBaseInfos;
    private javax.swing.JPanel patientMeasuresInfos;
    private javax.swing.JPanel patientWeightInfos;
    private javax.swing.JLabel rightArmLabel;
    private javax.swing.JLabel rightCalfLabel;
    private javax.swing.JLabel rightLegLabel;
    private javax.swing.JLabel sexLabel;
    private javax.swing.JLabel shouldersLabel;
    private javax.swing.JLabel waistLabel;
    // End of variables declaration//GEN-END:variables
}
