/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nutritionalprogram.View;

/**
 *
 * @author Luana Franciele
 */
public class PatientPanel extends javax.swing.JPanel {

    /**
     * Creates new form PatientPanel
     */
    public PatientPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        patientBaseInfos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        ageLabel = new javax.swing.JLabel();
        sexLabel = new javax.swing.JLabel();
        hightLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        patientWeightInfos = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        currentWeightLabel = new javax.swing.JLabel();
        goalWeightLabel = new javax.swing.JLabel();
        bodyfatLabel = new javax.swing.JLabel();
        imcLabel = new javax.swing.JLabel();
        differenceWeightLabel = new javax.swing.JLabel();
        patientMeasuresInfos = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        shouldersLabel = new javax.swing.JLabel();
        chestLabel = new javax.swing.JLabel();
        leftArmLabel = new javax.swing.JLabel();
        rightArmLabel = new javax.swing.JLabel();
        waistLabel = new javax.swing.JLabel();
        hipLabel = new javax.swing.JLabel();
        rightLegLabel = new javax.swing.JLabel();
        leftLegLabel = new javax.swing.JLabel();
        rightCalfLabel = new javax.swing.JLabel();
        leftCalfLabel = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        patientBaseInfos.setBackground(new java.awt.Color(102, 255, 102));
        patientBaseInfos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setText("Perfil do paciente");

        nameLabel.setText("Nome:");

        ageLabel.setText("Idade:");

        sexLabel.setText("Sexo:");

        hightLabel.setText("Altura:");

        javax.swing.GroupLayout patientBaseInfosLayout = new javax.swing.GroupLayout(patientBaseInfos);
        patientBaseInfos.setLayout(patientBaseInfosLayout);
        patientBaseInfosLayout.setHorizontalGroup(
            patientBaseInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patientBaseInfosLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(patientBaseInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameLabel)
                    .addComponent(ageLabel)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 211, Short.MAX_VALUE)
                .addGroup(patientBaseInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sexLabel)
                    .addComponent(hightLabel))
                .addGap(227, 227, 227))
        );
        patientBaseInfosLayout.setVerticalGroup(
            patientBaseInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patientBaseInfosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(patientBaseInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(sexLabel))
                .addGap(18, 18, 18)
                .addGroup(patientBaseInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageLabel)
                    .addComponent(hightLabel))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jButton1.setText("<-");

        jLabel2.setText("20/04/200");

        jButton2.setText("->");

        patientWeightInfos.setBackground(new java.awt.Color(102, 255, 102));

        jLabel6.setText("Peso do paciente");

        currentWeightLabel.setText("Atual:");

        goalWeightLabel.setText("Meta:");

        bodyfatLabel.setText("Taxa de gordura corporal:");

        imcLabel.setText("IMC:");

        differenceWeightLabel.setText("Diferença:");

        javax.swing.GroupLayout patientWeightInfosLayout = new javax.swing.GroupLayout(patientWeightInfos);
        patientWeightInfos.setLayout(patientWeightInfosLayout);
        patientWeightInfosLayout.setHorizontalGroup(
            patientWeightInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patientWeightInfosLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(patientWeightInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(patientWeightInfosLayout.createSequentialGroup()
                        .addGroup(patientWeightInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(currentWeightLabel)
                            .addComponent(bodyfatLabel))
                        .addGap(130, 130, 130)
                        .addGroup(patientWeightInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(imcLabel)
                            .addGroup(patientWeightInfosLayout.createSequentialGroup()
                                .addComponent(goalWeightLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(differenceWeightLabel)))))
                .addGap(160, 160, 160))
        );
        patientWeightInfosLayout.setVerticalGroup(
            patientWeightInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patientWeightInfosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(29, 29, 29)
                .addGroup(patientWeightInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(currentWeightLabel)
                    .addComponent(goalWeightLabel)
                    .addComponent(differenceWeightLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(patientWeightInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bodyfatLabel)
                    .addComponent(imcLabel))
                .addGap(30, 30, 30))
        );

        patientMeasuresInfos.setBackground(new java.awt.Color(102, 255, 102));
        patientMeasuresInfos.setPreferredSize(new java.awt.Dimension(0, 143));

        jLabel9.setText("Medidas");

        shouldersLabel.setText("Ombros:");

        chestLabel.setText("Peitoral:");

        leftArmLabel.setText("Braço e.:");

        rightArmLabel.setText("Braço d.:");

        waistLabel.setText("Cintura:");

        hipLabel.setText("Quadril:");

        rightLegLabel.setText("Perna d.:");

        leftLegLabel.setText("Perna e.:");

        rightCalfLabel.setText("Panturrilha d.:");

        leftCalfLabel.setText("Panturrilha e.:");

        javax.swing.GroupLayout patientMeasuresInfosLayout = new javax.swing.GroupLayout(patientMeasuresInfos);
        patientMeasuresInfos.setLayout(patientMeasuresInfosLayout);
        patientMeasuresInfosLayout.setHorizontalGroup(
            patientMeasuresInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, patientMeasuresInfosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(patientMeasuresInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chestLabel)
                    .addGroup(patientMeasuresInfosLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel9))
                    .addComponent(leftArmLabel)
                    .addComponent(rightArmLabel)
                    .addComponent(shouldersLabel)
                    .addComponent(waistLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 313, Short.MAX_VALUE)
                .addGroup(patientMeasuresInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(leftLegLabel)
                    .addComponent(leftCalfLabel)
                    .addComponent(hipLabel)
                    .addComponent(rightLegLabel)
                    .addComponent(rightCalfLabel))
                .addGap(233, 233, 233))
        );
        patientMeasuresInfosLayout.setVerticalGroup(
            patientMeasuresInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patientMeasuresInfosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(patientMeasuresInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shouldersLabel)
                    .addComponent(hipLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(patientMeasuresInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chestLabel)
                    .addComponent(rightLegLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(patientMeasuresInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(leftArmLabel)
                    .addComponent(leftLegLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(patientMeasuresInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rightArmLabel)
                    .addComponent(rightCalfLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(patientMeasuresInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(leftCalfLabel)
                    .addComponent(waistLabel))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jButton3.setText("Criar novo cardápio");

        jButton4.setText("Ver cardápios");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(jButton2)
                        .addGap(45, 45, 45))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(patientBaseInfos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(patientWeightInfos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(patientMeasuresInfos, javax.swing.GroupLayout.DEFAULT_SIZE, 669, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(patientBaseInfos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(patientWeightInfos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(patientMeasuresInfos, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ageLabel;
    private javax.swing.JLabel bodyfatLabel;
    private javax.swing.JLabel chestLabel;
    private javax.swing.JLabel currentWeightLabel;
    private javax.swing.JLabel differenceWeightLabel;
    private javax.swing.JLabel goalWeightLabel;
    private javax.swing.JLabel hightLabel;
    private javax.swing.JLabel hipLabel;
    private javax.swing.JLabel imcLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel leftArmLabel;
    private javax.swing.JLabel leftCalfLabel;
    private javax.swing.JLabel leftLegLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JPanel patientBaseInfos;
    private javax.swing.JPanel patientMeasuresInfos;
    private javax.swing.JPanel patientWeightInfos;
    private javax.swing.JLabel rightArmLabel;
    private javax.swing.JLabel rightCalfLabel;
    private javax.swing.JLabel rightLegLabel;
    private javax.swing.JLabel sexLabel;
    private javax.swing.JLabel shouldersLabel;
    private javax.swing.JLabel waistLabel;
    // End of variables declaration//GEN-END:variables
}
